name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

permissions:
  actions: read
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - run: npx nx run-many -t lint test

      - name: Build
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: npx nx build demo-app --configuration=production

      - run: npx nx fix-ci
        if: always()

      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/demo-app/browser
